// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package hyperliquid

import (
	"github.com/mailru/easyjson/jlexer"
	"github.com/mailru/easyjson/jwriter"
)

func (ApproveAgentAction) MarshalJSON() ([]byte, error)       { return nil, nil }
func (*ApproveAgentAction) UnmarshalJSON([]byte) error        { return nil }
func (ApproveAgentAction) MarshalEasyJSON(w *jwriter.Writer)  {}
func (*ApproveAgentAction) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_ApproveAgentAction *ApproveAgentAction

func (ApproveBuilderFeeAction) MarshalJSON() ([]byte, error)       { return nil, nil }
func (*ApproveBuilderFeeAction) UnmarshalJSON([]byte) error        { return nil }
func (ApproveBuilderFeeAction) MarshalEasyJSON(w *jwriter.Writer)  {}
func (*ApproveBuilderFeeAction) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_ApproveBuilderFeeAction *ApproveBuilderFeeAction

func (BatchModifyAction) MarshalJSON() ([]byte, error)       { return nil, nil }
func (*BatchModifyAction) UnmarshalJSON([]byte) error        { return nil }
func (BatchModifyAction) MarshalEasyJSON(w *jwriter.Writer)  {}
func (*BatchModifyAction) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_BatchModifyAction *BatchModifyAction

func (CancelAction) MarshalJSON() ([]byte, error)       { return nil, nil }
func (*CancelAction) UnmarshalJSON([]byte) error        { return nil }
func (CancelAction) MarshalEasyJSON(w *jwriter.Writer)  {}
func (*CancelAction) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_CancelAction *CancelAction

func (CancelByCloidAction) MarshalJSON() ([]byte, error)       { return nil, nil }
func (*CancelByCloidAction) UnmarshalJSON([]byte) error        { return nil }
func (CancelByCloidAction) MarshalEasyJSON(w *jwriter.Writer)  {}
func (*CancelByCloidAction) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_CancelByCloidAction *CancelByCloidAction

func (CancelByCloidWire) MarshalJSON() ([]byte, error)       { return nil, nil }
func (*CancelByCloidWire) UnmarshalJSON([]byte) error        { return nil }
func (CancelByCloidWire) MarshalEasyJSON(w *jwriter.Writer)  {}
func (*CancelByCloidWire) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_CancelByCloidWire *CancelByCloidWire

func (CancelOrderWire) MarshalJSON() ([]byte, error)       { return nil, nil }
func (*CancelOrderWire) UnmarshalJSON([]byte) error        { return nil }
func (CancelOrderWire) MarshalEasyJSON(w *jwriter.Writer)  {}
func (*CancelOrderWire) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_CancelOrderWire *CancelOrderWire

func (ConvertToMultiSigUserAction) MarshalJSON() ([]byte, error)       { return nil, nil }
func (*ConvertToMultiSigUserAction) UnmarshalJSON([]byte) error        { return nil }
func (ConvertToMultiSigUserAction) MarshalEasyJSON(w *jwriter.Writer)  {}
func (*ConvertToMultiSigUserAction) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_ConvertToMultiSigUserAction *ConvertToMultiSigUserAction

func (CreateSubAccountAction) MarshalJSON() ([]byte, error)       { return nil, nil }
func (*CreateSubAccountAction) UnmarshalJSON([]byte) error        { return nil }
func (CreateSubAccountAction) MarshalEasyJSON(w *jwriter.Writer)  {}
func (*CreateSubAccountAction) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_CreateSubAccountAction *CreateSubAccountAction

func (CreateVaultAction) MarshalJSON() ([]byte, error)       { return nil, nil }
func (*CreateVaultAction) UnmarshalJSON([]byte) error        { return nil }
func (CreateVaultAction) MarshalEasyJSON(w *jwriter.Writer)  {}
func (*CreateVaultAction) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_CreateVaultAction *CreateVaultAction

func (ModifyAction) MarshalJSON() ([]byte, error)       { return nil, nil }
func (*ModifyAction) UnmarshalJSON([]byte) error        { return nil }
func (ModifyAction) MarshalEasyJSON(w *jwriter.Writer)  {}
func (*ModifyAction) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_ModifyAction *ModifyAction

func (MultiSigAction) MarshalJSON() ([]byte, error)       { return nil, nil }
func (*MultiSigAction) UnmarshalJSON([]byte) error        { return nil }
func (MultiSigAction) MarshalEasyJSON(w *jwriter.Writer)  {}
func (*MultiSigAction) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_MultiSigAction *MultiSigAction

func (OrderAction) MarshalJSON() ([]byte, error)       { return nil, nil }
func (*OrderAction) UnmarshalJSON([]byte) error        { return nil }
func (OrderAction) MarshalEasyJSON(w *jwriter.Writer)  {}
func (*OrderAction) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_OrderAction *OrderAction

func (OrderWire) MarshalJSON() ([]byte, error)       { return nil, nil }
func (*OrderWire) UnmarshalJSON([]byte) error        { return nil }
func (OrderWire) MarshalEasyJSON(w *jwriter.Writer)  {}
func (*OrderWire) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_OrderWire *OrderWire

func (PerpDexClassTransferAction) MarshalJSON() ([]byte, error)       { return nil, nil }
func (*PerpDexClassTransferAction) UnmarshalJSON([]byte) error        { return nil }
func (PerpDexClassTransferAction) MarshalEasyJSON(w *jwriter.Writer)  {}
func (*PerpDexClassTransferAction) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_PerpDexClassTransferAction *PerpDexClassTransferAction

func (ScheduleCancelAction) MarshalJSON() ([]byte, error)       { return nil, nil }
func (*ScheduleCancelAction) UnmarshalJSON([]byte) error        { return nil }
func (ScheduleCancelAction) MarshalEasyJSON(w *jwriter.Writer)  {}
func (*ScheduleCancelAction) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_ScheduleCancelAction *ScheduleCancelAction

func (SetReferrerAction) MarshalJSON() ([]byte, error)       { return nil, nil }
func (*SetReferrerAction) UnmarshalJSON([]byte) error        { return nil }
func (SetReferrerAction) MarshalEasyJSON(w *jwriter.Writer)  {}
func (*SetReferrerAction) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_SetReferrerAction *SetReferrerAction

func (SpotTransferAction) MarshalJSON() ([]byte, error)       { return nil, nil }
func (*SpotTransferAction) UnmarshalJSON([]byte) error        { return nil }
func (SpotTransferAction) MarshalEasyJSON(w *jwriter.Writer)  {}
func (*SpotTransferAction) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_SpotTransferAction *SpotTransferAction

func (SubAccountSpotTransferAction) MarshalJSON() ([]byte, error)       { return nil, nil }
func (*SubAccountSpotTransferAction) UnmarshalJSON([]byte) error        { return nil }
func (SubAccountSpotTransferAction) MarshalEasyJSON(w *jwriter.Writer)  {}
func (*SubAccountSpotTransferAction) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_SubAccountSpotTransferAction *SubAccountSpotTransferAction

func (SubAccountTransferAction) MarshalJSON() ([]byte, error)       { return nil, nil }
func (*SubAccountTransferAction) UnmarshalJSON([]byte) error        { return nil }
func (SubAccountTransferAction) MarshalEasyJSON(w *jwriter.Writer)  {}
func (*SubAccountTransferAction) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_SubAccountTransferAction *SubAccountTransferAction

func (TokenDelegateAction) MarshalJSON() ([]byte, error)       { return nil, nil }
func (*TokenDelegateAction) UnmarshalJSON([]byte) error        { return nil }
func (TokenDelegateAction) MarshalEasyJSON(w *jwriter.Writer)  {}
func (*TokenDelegateAction) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_TokenDelegateAction *TokenDelegateAction

func (UpdateIsolatedMarginAction) MarshalJSON() ([]byte, error)       { return nil, nil }
func (*UpdateIsolatedMarginAction) UnmarshalJSON([]byte) error        { return nil }
func (UpdateIsolatedMarginAction) MarshalEasyJSON(w *jwriter.Writer)  {}
func (*UpdateIsolatedMarginAction) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_UpdateIsolatedMarginAction *UpdateIsolatedMarginAction

func (UpdateLeverageAction) MarshalJSON() ([]byte, error)       { return nil, nil }
func (*UpdateLeverageAction) UnmarshalJSON([]byte) error        { return nil }
func (UpdateLeverageAction) MarshalEasyJSON(w *jwriter.Writer)  {}
func (*UpdateLeverageAction) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_UpdateLeverageAction *UpdateLeverageAction

func (UsdClassTransferAction) MarshalJSON() ([]byte, error)       { return nil, nil }
func (*UsdClassTransferAction) UnmarshalJSON([]byte) error        { return nil }
func (UsdClassTransferAction) MarshalEasyJSON(w *jwriter.Writer)  {}
func (*UsdClassTransferAction) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_UsdClassTransferAction *UsdClassTransferAction

func (UsdTransferAction) MarshalJSON() ([]byte, error)       { return nil, nil }
func (*UsdTransferAction) UnmarshalJSON([]byte) error        { return nil }
func (UsdTransferAction) MarshalEasyJSON(w *jwriter.Writer)  {}
func (*UsdTransferAction) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_UsdTransferAction *UsdTransferAction

func (UseBigBlocksAction) MarshalJSON() ([]byte, error)       { return nil, nil }
func (*UseBigBlocksAction) UnmarshalJSON([]byte) error        { return nil }
func (UseBigBlocksAction) MarshalEasyJSON(w *jwriter.Writer)  {}
func (*UseBigBlocksAction) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_UseBigBlocksAction *UseBigBlocksAction

func (VaultDistributeAction) MarshalJSON() ([]byte, error)       { return nil, nil }
func (*VaultDistributeAction) UnmarshalJSON([]byte) error        { return nil }
func (VaultDistributeAction) MarshalEasyJSON(w *jwriter.Writer)  {}
func (*VaultDistributeAction) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_VaultDistributeAction *VaultDistributeAction

func (VaultModifyAction) MarshalJSON() ([]byte, error)       { return nil, nil }
func (*VaultModifyAction) UnmarshalJSON([]byte) error        { return nil }
func (VaultModifyAction) MarshalEasyJSON(w *jwriter.Writer)  {}
func (*VaultModifyAction) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_VaultModifyAction *VaultModifyAction

func (VaultUsdTransferAction) MarshalJSON() ([]byte, error)       { return nil, nil }
func (*VaultUsdTransferAction) UnmarshalJSON([]byte) error        { return nil }
func (VaultUsdTransferAction) MarshalEasyJSON(w *jwriter.Writer)  {}
func (*VaultUsdTransferAction) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_VaultUsdTransferAction *VaultUsdTransferAction

func (WithdrawFromBridgeAction) MarshalJSON() ([]byte, error)       { return nil, nil }
func (*WithdrawFromBridgeAction) UnmarshalJSON([]byte) error        { return nil }
func (WithdrawFromBridgeAction) MarshalEasyJSON(w *jwriter.Writer)  {}
func (*WithdrawFromBridgeAction) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_WithdrawFromBridgeAction *WithdrawFromBridgeAction

func (orderWireType) MarshalJSON() ([]byte, error)       { return nil, nil }
func (*orderWireType) UnmarshalJSON([]byte) error        { return nil }
func (orderWireType) MarshalEasyJSON(w *jwriter.Writer)  {}
func (*orderWireType) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_orderWireType *orderWireType

func (orderWireTypeLimit) MarshalJSON() ([]byte, error)       { return nil, nil }
func (*orderWireTypeLimit) UnmarshalJSON([]byte) error        { return nil }
func (orderWireTypeLimit) MarshalEasyJSON(w *jwriter.Writer)  {}
func (*orderWireTypeLimit) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_orderWireTypeLimit *orderWireTypeLimit

func (orderWireTypeTrigger) MarshalJSON() ([]byte, error)       { return nil, nil }
func (*orderWireTypeTrigger) UnmarshalJSON([]byte) error        { return nil }
func (orderWireTypeTrigger) MarshalEasyJSON(w *jwriter.Writer)  {}
func (*orderWireTypeTrigger) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_orderWireTypeTrigger *orderWireTypeTrigger
